kafka:
  address:
    - localhost:9092
  topic:
  chanMaxSize: 100000

etcd:
  address: localhost:2379
  timeout: 10
  logCollectKey: logPath

es:
  address: localhost:9200
  size: 100000
  worker: 10

logfilePath:
  /Users/tysonhu/GolandProjects/log-collect/test/log-1.log
