kafka:
  address:
    - localhost:9092
  topic:
  chanMaxSize: 100000

etcd:
  address: localhost:2379
  timeout: 5

es:
  address: localhost:9200
  size: 100000
  worker: 10

logfilePath:
  - /Users/tysonhu/GolandProjects/log-collect/test/log-1.log
  - /Users/tysonhu/GolandProjects/log-collect/test/log-2.log
#  - /var/www/erp.yms/storage/logs/access.log
#  - /var/www/erp.yms/storage/logs/error.log